# Generated by Django 3.2.11 on 2022-01-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('roll_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stud_class', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.CharField(max_length=3)),
                ('physics', models.CharField(max_length=3)),
                ('chemistry', models.CharField(max_length=3)),
                ('biology', models.CharField(max_length=3)),
                ('english', models.CharField(max_length=3)),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentinfo')),
            ],
        ),
    ]
