# Generated by Django 3.2.11 on 2022-01-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='Address',
            new_name='address',
        ),
    ]
